In [5]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

arr*arr
arr-arr
1/arr


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr-arr


array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
arr**0.5


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [13]:
#comparison between array of the same size yeald boolen arrays:
arr2=np.array([[0.,4.,1.,],[7.,2.,12.]])
arr2
arr2>arr
#evaluating operations between diffrently sized arrays is called -brodcasting


array([[False,  True, False],
       [ True, False,  True]])

In [7]:
arr-arr


array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
arr-arr


array([[0, 0, 0],
       [0, 0, 0]])