In [5]:
import numpy as np

names =np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

data =np.random.randn(7,4)

names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data


array([[ 0.87812399, -1.06454897, -1.20500914,  0.70734527],
       [ 1.33623135, -1.20159293,  0.9469173 ,  1.78003062],
       [-0.26989732, -2.06120794,  0.42701972, -0.71745625],
       [-1.14599019,  0.42678228, -1.2243276 , -1.23643047],
       [ 0.79324636,  1.96187477,  0.20297447, -1.00387291],
       [ 0.34413366, -0.11388841,  0.25444258,  0.57535799],
       [-1.20502365, -0.42120502,  0.67694261,  1.29579278]])

In [7]:
names=='Bob'



array([ True, False, False,  True, False, False, False])

In [8]:
data[names=='Bob']


array([[ 0.87812399, -1.06454897, -1.20500914,  0.70734527],
       [-1.14599019,  0.42678228, -1.2243276 , -1.23643047]])

In [9]:
data[names=='Bob',2:]


array([[-1.20500914,  0.70734527],
       [-1.2243276 , -1.23643047]])

In [10]:
data[names=='Bob',3]


array([ 0.70734527, -1.23643047])

In [11]:
names!='Bob'


array([False,  True,  True, False,  True,  True,  True])

In [12]:
~(names=='Bob')


array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[~(names=='Bob')]
#had issue here need fixes
#supposed to print everythig else except the "Bob " rows


array([[ 1.33623135, -1.20159293,  0.9469173 ,  1.78003062],
       [-0.26989732, -2.06120794,  0.42701972, -0.71745625],
       [ 0.79324636,  1.96187477,  0.20297447, -1.00387291],
       [ 0.34413366, -0.11388841,  0.25444258,  0.57535799],
       [-1.20502365, -0.42120502,  0.67694261,  1.29579278]])

In [14]:
cond=names==True
print(data[~cond])

#somehow notworking for me but seems like a good idea


[[ 0.87812399 -1.06454897 -1.20500914  0.70734527]
 [ 1.33623135 -1.20159293  0.9469173   1.78003062]
 [-0.26989732 -2.06120794  0.42701972 -0.71745625]
 [-1.14599019  0.42678228 -1.2243276  -1.23643047]
 [ 0.79324636  1.96187477  0.20297447 -1.00387291]
 [ 0.34413366 -0.11388841  0.25444258  0.57535799]
 [-1.20502365 -0.42120502  0.67694261  1.29579278]]


In [15]:

#need more reserch
data[data<0]=0
