In [1]:
import numpy as np

names =np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

data =np.random.randn(7,4)

names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [2]:
data


array([[-0.02377031,  0.02554022, -0.39028706,  0.02642496],
       [ 0.8407925 ,  0.92536715, -0.30340684,  0.270455  ],
       [-2.01641113, -0.08080192,  1.28469462, -0.68091584],
       [-0.27842796,  0.94916926,  0.45646888,  1.73651304],
       [-1.75684084, -0.59572614,  0.43337271, -0.75818753],
       [-1.23017648, -1.06891901, -0.38431139, -0.28661128],
       [ 2.37876317,  0.45397842, -0.17429424, -1.17100799]])

In [4]:
names=='Bob'



array([ True, False, False,  True, False, False, False])

In [5]:
data[names=='Bob']


array([[-0.02377031,  0.02554022, -0.39028706,  0.02642496],
       [-0.27842796,  0.94916926,  0.45646888,  1.73651304]])

In [7]:
data[names=='Bob',2:]


array([[-0.39028706,  0.02642496],
       [ 0.45646888,  1.73651304]])

In [8]:
data[names=='Bob',3]


array([0.02642496, 1.73651304])

In [10]:
names!='Bob'


array([False,  True,  True, False,  True,  True,  True])

In [12]:
~(names=='Bob')


array([False,  True,  True, False,  True,  True,  True])

In [3]:
data[~(names=='Bob')]
#had issue here need fixes
#supposed to print everythig else except the "Bob " rows


NameError: name 'data' is not defined

In [24]:
cond=names==TRUE
print(data[~cond])

#somehow notworking for me but seems like a good idea


NameError: name 'TRUE' is not defined

In [25]:

#need more reserch
data[data<0]=0


TypeError: '<' not supported between instances of 'list' and 'int'