In [7]:
import numpy as np
#fancy indexing is term adopted by NumPy to describe indexing using integer arrays.

arr=np.empty((8,4))

for i in range(8):
    arr[i]=i


arr


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [8]:
#select out a subset of the rows in a particular order
arr[[4,3,0,6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [12]:
#TRANSPOSING ARRAYS AND SWAPPING AXES
#*special form of reshaping
#*return a view of the data without copying anything

arr=np.arange(15).reshape((3,5))

arr



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
arr.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [14]:
arr=np.random.randn(6,3)

arr


array([[ 1.13103672e+00, -7.62244205e-01,  1.21717583e+00],
       [ 1.17865587e-01,  5.77350890e-01, -1.48880320e+00],
       [ 8.06132272e-01, -3.26069872e-01,  4.15555912e-01],
       [ 1.63266240e-03,  1.18881339e+00,  3.48002203e-01],
       [ 2.19813096e-01, -9.39042484e-02,  1.67970034e+00],
       [-1.03047367e+00,  1.10967784e+00, -9.66313250e-01]])

In [15]:
np.dot(arr.T,arr)


array([[ 3.05318205, -2.21912608,  2.90173359],
       [-2.21912608,  3.67415202, -2.73916505],
       [ 2.90173359, -2.73916505,  7.74699876]])

In [17]:
#another way to do matrix multiplication

arr.T@arr


array([[ 3.05318205, -2.21912608,  2.90173359],
       [-2.21912608,  3.67415202, -2.73916505],
       [ 2.90173359, -2.73916505,  7.74699876]])

In [19]:
#for higer dim arry transpose will accept a tuple of axis numbers to permute the axis
arr=np.arange(16).reshape((2,2,4))

arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
arr.transpose((1,0,2))




array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [22]:
arr
arr.swapaxes(1,2)


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])