In [14]:
import numpy as np
rng = np.random.default_rng()
arr=rng.standard_normal((5,4))
arr

array([[ 0.61204293,  0.94331309,  2.06589263,  1.78547986],
       [ 0.04190858, -0.11169931,  0.18042574, -0.10490247],
       [-0.46773989,  0.89286636, -0.99705208,  1.57489859],
       [-0.60883501, -0.68359476, -1.42633515,  0.18680078],
       [-0.65513988, -1.15258161, -0.28162184,  0.13681044]])

In [18]:
print(arr.mean())
print(np.mean(arr))
arr.sum()

#here arr.mean(axis=1 )means COMPUTE MEAN ACROSS COLUMNS
#AND arr.sum(axis=0)means COMPUTE SUM DOWN THE ROWS
print(arr.mean(axis=1))
print (arr.sum(axis=0))


0.09654685000853801
0.09654685000853801
[ 1.35168213  0.00143314  0.25074325 -0.63299104 -0.48813322]
[-1.07776326 -0.11169623 -0.4586907   3.57908719]


In [20]:
arr=np.array([0,1,2,3,4,5,6,7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [ ]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])