In [5]:
import numpy as np
rng = np.random.default_rng()
arr=rng.standard_normal((5,4))
arr

array([[ 1.118491  , -0.59601693,  1.42767294, -0.30769892],
       [-0.20052601,  0.05828972, -0.01895993,  1.02330017],
       [ 0.4021533 , -0.63409345, -1.26372905,  1.07977945],
       [ 0.11761854, -0.17042764, -0.87227816, -2.1456426 ],
       [-1.78556033, -0.48916178, -0.73786597,  0.23781693]])

In [6]:
print(arr.mean())
print(np.mean(arr))
arr.sum()

#here arr.mean(axis=1 )means COMPUTE MEAN ACROSS COLUMNS
#AND arr.sum(axis=0)means COMPUTE SUM DOWN THE ROWS
print(arr.mean(axis=1))
print (arr.sum(axis=0))


-0.18784193555014955
-0.18784193555014955
[ 0.41061203  0.21552599 -0.10397244 -0.76768246 -0.69369279]
[-0.34782349 -1.83141008 -1.46516016 -0.11244497]


In [7]:
arr=np.array([0,1,2,3,4,5,6,7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [8]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])