In [3]:
#the numpy ndarray: a multidimensional array object

import numpy as np
data=np.array([[ 1.5,-0.1,3],[0,-3,0.5]])




array([[ 3. , -0.2,  6. ],
       [ 0. , -6. ,  1. ]])

In [6]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. ,  1. ]])

In [5]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,   5.]])