In [7]:
#  the numpy ndarray: a multidimensional array object

import numpy as np
data1=[6,7,5,8,9,1]
arr1=np.array(data1)
arr1

array([6, 7, 5, 8, 9, 1])

In [15]:
data2=[[1,2,3,4,],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)
#show the dimesion
print(arr2.ndim)
#print the shape
print(2,4)

#type is stored in a special dtpe metadata object. 
print(arr1.dtype)



[[1 2 3 4]
 [5 6 7 8]]
2
2 4
int64


In [21]:
print(np.zeros(10))

print('\n',np.zeros((3,6)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
