In [2]:
#pesudo random number generator
import numpy as np 
sample=np.random.standard_normal(size=(4,4))
sample

array([[ 0.10826539, -0.25084185, -0.08181711, -0.09141519],
       [ 0.61576833, -0.64874695,  0.77158553,  0.88662512],
       [ 0.3306921 , -0.69769619,  0.92231973,  0.90403233],
       [ 1.00127422, -1.16990365,  1.37923256,  0.1878384 ]])

In [4]:
from random import normalvariate
N= 1_000_000

sample=[normalvariate(0,1)for _ in range(N)]
sample

[-0.08688228412137075,
 -0.17509600461436817,
 0.14002291610637996,
 -1.153844003995793,
 0.15664781132864894,
 -0.602403006520316,
 -1.3359035545718039,
 0.9413760644403893,
 -1.172674098183728,
 1.050199577542959,
 0.26011169928444877,
 1.1750235883265334,
 -0.4835343234067976,
 0.4941848724203861,
 0.5310584574922472,
 1.3137789094824464,
 -2.0510530719194797,
 -0.33546318679731196,
 -0.5099585342841589,
 -1.2319314908983978,
 -0.8871621516350577,
 0.3649569379843794,
 -0.2689136761228032,
 0.2476856108916378,
 -0.4125836678354372,
 1.3164770931474714,
 -0.34001556771612973,
 -0.0028196434228851043,
 -0.46448478014580047,
 0.159499478875597,
 -1.6574841675026442,
 -0.9462443583221145,
 -0.3379875129386109,
 -1.3532846847773194,
 2.103247811187177,
 0.5689901744689008,
 -1.382723459808749,
 0.5217359069647357,
 -0.3781792146563162,
 -0.8043949514470352,
 1.002141160512624,
 0.3710992556615011,
 -0.5072300746845261,
 0.495997939814733,
 -0.2998529522805168,
 0.41169823438515896,
 -0.7

In [5]:
rng=np.random.default_rng(seed=12345)
data=rng.standard_normal((2,3))
type(rng)

numpy.random._generator.Generator

In [7]:
#Universal Functions:Fast Element-Wise Array Functions
#* a univarsal functon ,or ufunc, is a function that performs element-wise operation on data in ndarrays
arr=np.arange(10)
arr
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
x=rng.standard_normal(8)
y=rng.standard_normal(8)
print(x)
print(y)

np.maximum(x,y)


[-1.22867499  0.25755777  0.31290292 -0.13081169  1.26998312 -0.09296246
 -0.06615089 -1.10821447]
[0.13595685 1.34707776 0.06114402 0.0709146  0.43365454 0.27748366
 0.53025239 0.53672097]


array([0.13595685, 1.34707776, 0.31290292, 0.0709146 , 1.26998312,
       0.27748366, 0.53025239, 0.53672097])