In [18]:
import numpy as np

arr=np.arange(10)
print(arr)
print(arr[5])



[0 1 2 3 4 5 6 7 8 9]
5


In [19]:
#* arry slices are veiws
#* means, the data is not copied
#* any modifiction to the view will be reflected in the source array
arr[5:8]


array([5, 6, 7])

In [20]:
arr[5:8]=12
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [22]:
arr_slice=arr[5:8]
arr_slice


array([12, 12, 12])

In [24]:
arr_slice[2]=12345
arr
#NOTE
#* if you want a copy of a slice of an ndarray of a view, you will need to explicitly copy the array 
#eg arr[5:8].copy


#there is the "bare slice [:]"


array([    0,     1,     2,     3,     4,    12, 12345, 12345,     8,
           9])

In [26]:
arr2d=([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]
arr2d[0][3]
arr2d[0][2]
#self explanatory


[7, 8, 9]

In [30]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,23]]])
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 23]]])

In [31]:
#arr3d[0]is a 2*3 array
arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
old_values=arr3d[0].copy()
arr3d[0]=42

arr3d

arr3d[0]=old_values

print(arr3d)
#somthing should happen here


[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 23]]]


In [36]:
print(arr3d[1,0,0])
#NOTE *SAME AS
x=arr3d[1]
x
#prints something here

x[0]
#does something here


7


array([7, 8, 9])

In [43]:
#INDEXIG WIHT SLICE
arr2d
arr2d[:2]


[[1, 2, 3], [4, 5, 6]]

In [46]:
arr2d[:2, 1:]
print(arr2d)
#this did not work for somereason


TypeError: list indices must be integers or slices, not tuple